package setupwizard

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/ai-coding-assistant/model"
	"github.com/google/uuid"
	"golang.org/x/crypto/bcrypt"
	"gorm.io/gorm"
)

type (
	logFunc   func(level string, msg string)
	phaseFunc func(phase string)
)

func PerformSetup(ctx context.Context, pre *Preflight, cfg SetupConfig, logf logFunc, setPhase phaseFunc) (backendURL string, frontendURL string, err error) {
	if pre == nil {
		return "", "", errors.New("preflight is required")
	}

	log := func(level, msg string) {
		if logf != nil {
			logf(level, msg)
		}
	}
	phase := func(p string) {
		if setPhase != nil {
			setPhase(p)
		}
	}

	phase("validate")
	if err := validateAndNormalize(&cfg, pre, log); err != nil {
		return "", "", err
	}

	runtimeDir := pre.RuntimeDir
	logDir := filepath.Join(runtimeDir, "logs")
	pidDir := filepath.Join(runtimeDir, "pids")
	goCacheDir := filepath.Join(runtimeDir, "go-build-cache")
	goTmpDir := filepath.Join(runtimeDir, "go-tmp")
	goPathDir := filepath.Join(runtimeDir, "go")
	npmCacheDir := filepath.Join(runtimeDir, "npm-cache")

	for _, dir := range []string{logDir, pidDir, goCacheDir, goTmpDir, goPathDir, npmCacheDir} {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return "", "", err
		}
	}

	phase("write_env")
	envMap := buildEnvMap(cfg, pre)
	if err := writeDotEnvFile(pre.EnvPath, envMap, dotenvWriteOptions{
		headerComment: "Generated by AI Coding Assistant setup wizard",
		mode:          0600,
	}); err != nil {
		return "", "", err
	}
	log("info", fmt.Sprintf("Wrote %s", pre.EnvPath))

	dbDSN, err := resolveDatabaseDSN(pre, cfg.DatabaseType, cfg.DatabaseDSN)
	if err != nil {
		return "", "", err
	}
	if cfg.DatabaseType == "" || cfg.DatabaseType == "sqlite" {
		if dbDSN != "" &&
			dbDSN != ":memory:" &&
			!strings.HasPrefix(dbDSN, "file:") &&
			!strings.Contains(dbDSN, "://") {
			if err := os.MkdirAll(filepath.Dir(dbDSN), 0755); err != nil {
				return "", "", err
			}
		}
	}

	phase("init_db")
	log("info", fmt.Sprintf("Initializing %s database…", cfg.DatabaseType))
	if err := seedDatabase(cfg.DatabaseType, dbDSN, cfg, log); err != nil {
		return "", "", err
	}
	log("success", "Database initialized.")

	if cfg.FrontendMode == "embedded" && cfg.BuildFrontend {
		if !pre.HasNode || !pre.HasNpm {
			return "", "", errors.New("Node.js/npm is required to build frontend (npm run build)")
		}
		if cfg.InstallDeps {
			phase("npm_ci")
			if err := npmInstall(pre, npmCacheDir, log); err != nil {
				return "", "", err
			}
		}
		phase("npm_build")
		if err := npmBuild(pre, npmCacheDir, log); err != nil {
			return "", "", err
		}
	}

	if cfg.FrontendMode == "embedded" && !cfg.BuildFrontend && !pre.HasEmbeddedFrontend {
		// Static assets missing; require Node build.
		if !pre.HasNode || !pre.HasNpm {
			return "", "", errors.New("embedded frontend assets are missing; install Node.js to build frontend")
		}
		if cfg.InstallDeps {
			phase("npm_ci")
			if err := npmInstall(pre, npmCacheDir, log); err != nil {
				return "", "", err
			}
		}
		phase("npm_build")
		if err := npmBuild(pre, npmCacheDir, log); err != nil {
			return "", "", err
		}
	}

	backendPIDPath := filepath.Join(pidDir, "backend.pid")
	backendLogPath := filepath.Join(logDir, "backend.log")

	phase("start_backend")
	if cfg.BackendMode == "binary" {
		if !pre.HasBackendBinary {
			if !pre.HasGo {
				return "", "", errors.New("backend binary not found; install Go to build it or provide backend/ai-coding-assistant")
			}
			log("info", "Building backend binary…")
			phase("go_build")
			if err := goBuildBackend(pre, goCacheDir, goTmpDir, goPathDir, log); err != nil {
				return "", "", err
			}
		}
		phase("start_backend")
		log("info", "Starting backend (binary)…")
		if err := startProcessDetached(pre.BackendBinary, pre.BackendDir, envMap, backendLogPath, backendPIDPath, map[string]string{
			"GOCACHE":   goCacheDir,
			"GOTMPDIR":  goTmpDir,
			"GOPATH":    goPathDir,
			"GOMODCACHE": filepath.Join(goPathDir, "pkg", "mod"),
		}); err != nil {
			return "", "", err
		}
	} else {
		if !pre.HasGo {
			return "", "", errors.New("Go is required for backend go-run mode")
		}
		phase("start_backend")
		log("info", "Starting backend (go run)…")
		if err := startProcessDetached("go", pre.BackendDir, envMap, backendLogPath, backendPIDPath, map[string]string{
			"GOCACHE":   goCacheDir,
			"GOTMPDIR":  goTmpDir,
			"GOPATH":    goPathDir,
			"GOMODCACHE": filepath.Join(goPathDir, "pkg", "mod"),
		}, "run", "."); err != nil {
			return "", "", err
		}
	}

	backendURL = formatURL(cfg.ServerHost, cfg.ServerPort)
	phase("wait_backend")
	backendHealthURL := "http://" + net.JoinHostPort(localProbeHost(cfg.ServerHost), fmt.Sprint(cfg.ServerPort)) + "/api/health"
	if err := waitHTTPReady(ctx, backendHealthURL, 25*time.Second); err != nil {
		return "", "", fmt.Errorf("backend did not become healthy: %w", err)
	}

	frontendURL = backendURL
	if cfg.FrontendMode == "dev" {
		phase("start_frontend")
		if !pre.HasNode || !pre.HasNpm {
			return "", "", errors.New("Node.js/npm is required for frontend dev mode")
		}
		if cfg.InstallDeps {
			phase("npm_ci")
			if err := npmInstall(pre, npmCacheDir, log); err != nil {
				return "", "", err
			}
		}

		frontendPIDPath := filepath.Join(pidDir, "frontend.pid")
		frontendLogPath := filepath.Join(logDir, "frontend.log")

		phase("start_frontend")
		log("info", "Starting frontend (Vite dev)…")
		if err := startProcessDetached("npm", pre.FrontendDir, envMap, frontendLogPath, frontendPIDPath, map[string]string{
			"npm_config_cache": npmCacheDir,
			"ACA_BACKEND_HOST": "localhost",
			"ACA_BACKEND_PORT": fmt.Sprint(cfg.ServerPort),
			"ACA_FRONTEND_PORT": fmt.Sprint(cfg.FrontendPort),
		}, "run", "dev", "--", "--host", "0.0.0.0", "--port", fmt.Sprint(cfg.FrontendPort)); err != nil {
			return "", "", err
		}
		frontendURL = formatURL(cfg.ServerHost, cfg.FrontendPort)
		phase("wait_frontend")
		frontendReadyURL := "http://" + net.JoinHostPort(localProbeHost(cfg.ServerHost), fmt.Sprint(cfg.FrontendPort)) + "/"
		if err := waitHTTPReady(ctx, frontendReadyURL, 25*time.Second); err != nil {
			return "", "", fmt.Errorf("frontend did not become healthy: %w", err)
		}
	}

	phase("done")
	log("success", "Services started.")
	log("info", "Backend: "+backendURL)
	log("info", "Frontend: "+frontendURL)
	return backendURL, frontendURL, nil
}

func validateAndNormalize(cfg *SetupConfig, pre *Preflight, log logFunc) error {
	if cfg == nil {
		return errors.New("config is nil")
	}

	cfg.BackendMode = strings.TrimSpace(strings.ToLower(cfg.BackendMode))
	if cfg.BackendMode == "" {
		cfg.BackendMode = "binary"
	}
	if cfg.BackendMode != "binary" && cfg.BackendMode != "go-run" {
		return fmt.Errorf("invalid backend_mode: %s", cfg.BackendMode)
	}

	cfg.FrontendMode = strings.TrimSpace(strings.ToLower(cfg.FrontendMode))
	if cfg.FrontendMode == "" {
		cfg.FrontendMode = "embedded"
	}
	if cfg.FrontendMode != "embedded" && cfg.FrontendMode != "dev" {
		return fmt.Errorf("invalid frontend_mode: %s", cfg.FrontendMode)
	}

	cfg.ServerHost = strings.TrimSpace(cfg.ServerHost)
	if cfg.ServerHost == "" {
		cfg.ServerHost = pre.DefaultHost
	}
	if cfg.ServerHost == "" {
		cfg.ServerHost = "0.0.0.0"
	}

	if cfg.ServerPort <= 0 || cfg.ServerPort > 65535 {
		cfg.ServerPort = pre.RecommendedPort
	}

	port, err := pickAvailableTCPPort(cfg.ServerHost, cfg.ServerPort)
	if err != nil {
		return err
	}
	if port != cfg.ServerPort {
		log("warn", fmt.Sprintf("Backend port %d is in use; switching to %d", cfg.ServerPort, port))
		cfg.ServerPort = port
	}

	if cfg.FrontendPort <= 0 || cfg.FrontendPort > 65535 {
		cfg.FrontendPort = pre.RecommendedFrontDev
	}
	if cfg.FrontendMode == "dev" {
		p, err := pickAvailableTCPPort(cfg.ServerHost, cfg.FrontendPort)
		if err != nil {
			return err
		}
		if p != cfg.FrontendPort {
			log("warn", fmt.Sprintf("Frontend port %d is in use; switching to %d", cfg.FrontendPort, p))
			cfg.FrontendPort = p
		}
	}

	cfg.DatabaseType = strings.TrimSpace(strings.ToLower(cfg.DatabaseType))
	if cfg.DatabaseType == "" {
		cfg.DatabaseType = "sqlite"
	}
	if cfg.DatabaseType == "postgresql" {
		cfg.DatabaseType = "postgres"
	}
	if cfg.DatabaseType != "sqlite" && cfg.DatabaseType != "postgres" {
		return fmt.Errorf("invalid database_type: %s", cfg.DatabaseType)
	}

	cfg.DatabaseDSN = strings.TrimSpace(cfg.DatabaseDSN)
	if cfg.DatabaseDSN == "" {
		if cfg.DatabaseType == "sqlite" {
			cfg.DatabaseDSN = "./data/aca.db"
		} else {
			return errors.New("database_dsn is required for postgres")
		}
	}

	cfg.AdminUsername = strings.TrimSpace(cfg.AdminUsername)
	if cfg.AdminUsername == "" {
		cfg.AdminUsername = "admin"
	}
	cfg.AdminEmail = strings.TrimSpace(cfg.AdminEmail)
	cfg.AdminPassword = strings.TrimSpace(cfg.AdminPassword)
	if cfg.AdminPassword == "" {
		return errors.New("admin_password is required")
	}
	if len(cfg.AdminPassword) < 6 {
		return errors.New("admin_password must be at least 6 characters")
	}

	cfg.JWTSecret = strings.TrimSpace(cfg.JWTSecret)
	if cfg.JWTSecret == "" || strings.EqualFold(cfg.JWTSecret, "auto") {
		cfg.JWTSecret = uuid.NewString() + uuid.NewString()
	}

	cfg.TerminalDefaultLoginDir = strings.TrimSpace(cfg.TerminalDefaultLoginDir)
	if cfg.TerminalDefaultLoginDir == "" {
		cfg.TerminalDefaultLoginDir = "~/"
	}

	if strings.TrimSpace(cfg.SystemRule.Name) == "" {
		cfg.SystemRule.Name = "系统默认规则"
	}
	if strings.TrimSpace(cfg.SystemRule.ApprovalMode) == "" {
		cfg.SystemRule.ApprovalMode = "manual"
	}
	if strings.TrimSpace(cfg.SystemRule.AutoInputType) == "" {
		cfg.SystemRule.AutoInputType = "yes"
	}
	if cfg.SystemRule.ContextLines <= 0 {
		cfg.SystemRule.ContextLines = 50
	}

	return nil
}

func buildEnvMap(cfg SetupConfig, pre *Preflight) map[string]string {
	env := make(map[string]string)

	// Keep a few existing values if present.
	if pre != nil && pre.EnvValues != nil {
		for _, key := range []string{"TERMINAL_SHELL", "LOG_LEVEL", "LOG_FILE"} {
			if v := strings.TrimSpace(pre.EnvValues[key]); v != "" {
				env[key] = v
			}
		}
	}

	env["SERVER_HOST"] = cfg.ServerHost
	env["SERVER_PORT"] = fmt.Sprint(cfg.ServerPort)
	env["DEMO_MODE"] = fmt.Sprint(cfg.DemoMode)
	env["DATABASE_TYPE"] = cfg.DatabaseType
	env["DATABASE_DSN"] = cfg.DatabaseDSN

	env["AUTH_USERNAME"] = cfg.AdminUsername
	env["AUTH_PASSWORD"] = cfg.AdminPassword
	env["JWT_SECRET"] = cfg.JWTSecret

	env["TERMINAL_DEFAULT_LOGIN_DIR"] = cfg.TerminalDefaultLoginDir

	if _, ok := env["TERMINAL_SHELL"]; !ok {
		env["TERMINAL_SHELL"] = "/bin/bash"
	}
	if _, ok := env["LOG_LEVEL"]; !ok {
		env["LOG_LEVEL"] = "info"
	}
	if _, ok := env["LOG_FILE"]; !ok {
		env["LOG_FILE"] = ""
	}

	// Optional: used by scripts and Vite proxy.
	env["ACA_BACKEND_MODE"] = cfg.BackendMode
	env["ACA_FRONTEND_MODE"] = cfg.FrontendMode
	env["ACA_FRONTEND_PORT"] = fmt.Sprint(cfg.FrontendPort)
	env["ACA_BACKEND_HOST"] = "localhost"
	env["ACA_BACKEND_PORT"] = fmt.Sprint(cfg.ServerPort)

	return env
}

func resolveDatabaseDSN(pre *Preflight, databaseType string, dsn string) (string, error) {
	raw := strings.TrimSpace(dsn)
	if raw == "" {
		return "", errors.New("database dsn is empty")
	}

	if databaseType == "postgres" || databaseType == "postgresql" {
		return raw, nil
	}

	if raw == ":memory:" || strings.HasPrefix(raw, "file:") || strings.Contains(raw, "://") {
		// Let sqlite driver handle it.
		return raw, nil
	}
	if filepath.IsAbs(raw) {
		return raw, nil
	}

	backendDir := pre.BackendDir
	if backendDir == "" {
		return filepath.Clean(raw), nil
	}
	return filepath.Clean(filepath.Join(backendDir, raw)), nil
}

func seedDatabase(databaseType string, dsn string, cfg SetupConfig, log logFunc) error {
	db, err := model.InitDatabase(model.DBConfig{
		Type: databaseType,
		DSN:  dsn,
	})
	if err != nil {
		return err
	}
	model.DB = db
	model.LogDB = db
	defer func() {
		if model.DB != nil {
			if sqlDB, err := model.DB.DB(); err == nil && sqlDB != nil {
				_ = sqlDB.Close()
			}
		}
		model.DB = nil
	}()

	hashed, err := bcrypt.GenerateFromPassword([]byte(cfg.AdminPassword), bcrypt.DefaultCost)
	if err != nil {
		return err
	}

	var admin model.User
	query := model.DB.Where("username = ?", cfg.AdminUsername)
	if strings.TrimSpace(cfg.AdminEmail) != "" {
		query = query.Or("email = ?", cfg.AdminEmail)
	}
	findErr := query.First(&admin).Error
	if errors.Is(findErr, gorm.ErrRecordNotFound) {
		email := strings.TrimSpace(cfg.AdminEmail)
		if email == "" {
			email = fmt.Sprintf("%s@local", cfg.AdminUsername)
		}

		admin = model.User{
			ID:           uuid.NewString(),
			Username:     cfg.AdminUsername,
			Email:        email,
			PasswordHash: string(hashed),
			Role:         "admin",
			Status:       "active",
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		}
		if err := model.DB.Create(&admin).Error; err != nil {
			return err
		}
		log("info", fmt.Sprintf("Created admin user: %s", cfg.AdminUsername))
	} else if findErr != nil {
		return findErr
	} else {
		updates := map[string]any{
			"password_hash": string(hashed),
			"role":          "admin",
			"status":        "active",
			"updated_at":    time.Now(),
		}
		if strings.TrimSpace(cfg.AdminEmail) != "" {
			updates["email"] = strings.TrimSpace(cfg.AdminEmail)
		}
		if err := model.DB.Model(&model.User{}).Where("id = ?", admin.ID).Updates(updates).Error; err != nil {
			return err
		}
		log("info", fmt.Sprintf("Updated admin user: %s", admin.Username))
	}

	var ruleSet model.RuleSet
	result := model.DB.First(&ruleSet, "type = ?", "system")
	now := time.Now()
	if errors.Is(result.Error, gorm.ErrRecordNotFound) {
		ruleSet = model.RuleSet{
			ID:               "system-default",
			Name:             cfg.SystemRule.Name,
			Type:             "system",
			ApprovalMode:     cfg.SystemRule.ApprovalMode,
			AutoInputType:    cfg.SystemRule.AutoInputType,
			WhitelistPatterns: toJSONArray(cfg.SystemRule.Whitelist),
			BlacklistPatterns: toJSONArray(cfg.SystemRule.Blacklist),
			ContextLines:     cfg.SystemRule.ContextLines,
			DetectClaudeCode: cfg.SystemRule.DetectClaude,
			DetectCodex:      cfg.SystemRule.DetectCodex,
			DetectGemini:     cfg.SystemRule.DetectGemini,
			NotifyOnBlock:    cfg.SystemRule.NotifyOnBlock,
			NotifyOnApprove:  cfg.SystemRule.NotifyOnOK,
			CreatedAt:        now,
			UpdatedAt:        now,
		}
		if err := model.DB.Create(&ruleSet).Error; err != nil {
			return err
		}
		log("info", "Created default system rule set.")
	} else if result.Error == nil {
		updates := map[string]any{
			"name":               cfg.SystemRule.Name,
			"approval_mode":      cfg.SystemRule.ApprovalMode,
			"auto_input_type":    cfg.SystemRule.AutoInputType,
			"whitelist_patterns": toJSONArray(cfg.SystemRule.Whitelist),
			"blacklist_patterns": toJSONArray(cfg.SystemRule.Blacklist),
			"context_lines":      cfg.SystemRule.ContextLines,
			"detect_claude_code": cfg.SystemRule.DetectClaude,
			"detect_codex":       cfg.SystemRule.DetectCodex,
			"detect_gemini":      cfg.SystemRule.DetectGemini,
			"notify_on_block":    cfg.SystemRule.NotifyOnBlock,
			"notify_on_approve":  cfg.SystemRule.NotifyOnOK,
			"updated_at":         now,
		}
		if err := model.DB.Model(&model.RuleSet{}).Where("id = ?", ruleSet.ID).Updates(updates).Error; err != nil {
			return err
		}
		log("info", "Updated system rule set.")
	} else {
		return result.Error
	}

	return nil
}

func npmInstall(pre *Preflight, npmCache string, log logFunc) error {
	if pre == nil {
		return errors.New("preflight is nil")
	}
	if !pre.HasNpm {
		return errors.New("npm not found")
	}
	if _, err := os.Stat(filepath.Join(pre.FrontendDir, "package.json")); err != nil {
		return errors.New("frontend/package.json not found")
	}
	if info, err := os.Stat(filepath.Join(pre.FrontendDir, "node_modules")); err == nil && info.IsDir() {
		log("info", "frontend/node_modules exists; skipping npm ci.")
		return nil
	}

	log("info", "Installing frontend deps (npm ci)…")
	return runCommand(pre.FrontendDir, map[string]string{"npm_config_cache": npmCache}, "npm", "ci")
}

func npmBuild(pre *Preflight, npmCache string, log logFunc) error {
	if pre == nil {
		return errors.New("preflight is nil")
	}
	log("info", "Building frontend (npm run build)…")
	return runCommand(pre.FrontendDir, map[string]string{"npm_config_cache": npmCache}, "npm", "run", "build")
}

func goBuildBackend(pre *Preflight, goCache, goTmp, goPath string, log logFunc) error {
	if pre == nil {
		return errors.New("preflight is nil")
	}
	return runCommand(pre.BackendDir, map[string]string{
		"GOCACHE":   goCache,
		"GOTMPDIR":  goTmp,
		"GOPATH":    goPath,
		"GOMODCACHE": filepath.Join(goPath, "pkg", "mod"),
	}, "go", "build", "-o", pre.BackendBinary, ".")
}

func runCommand(dir string, extraEnv map[string]string, command string, args ...string) error {
	cmd := exec.Command(command, args...)
	cmd.Dir = dir
	cmd.Env = mergeEnviron(os.Environ(), extraEnv)
	out, err := cmd.CombinedOutput()
	if err != nil {
		msg := strings.TrimSpace(string(out))
		if msg == "" {
			msg = err.Error()
		}
		return fmt.Errorf("%s: %s", command, msg)
	}
	return nil
}

func mergeEnviron(base []string, overrides map[string]string) []string {
	if overrides == nil || len(overrides) == 0 {
		return base
	}
	m := make(map[string]string, len(base))
	order := make([]string, 0, len(base))
	for _, kv := range base {
		k, v, ok := strings.Cut(kv, "=")
		if !ok {
			continue
		}
		if _, exists := m[k]; !exists {
			order = append(order, k)
		}
		m[k] = v
	}
	for k, v := range overrides {
		if _, exists := m[k]; !exists {
			order = append(order, k)
		}
		m[k] = v
	}
	out := make([]string, 0, len(order))
	for _, k := range order {
		out = append(out, k+"="+m[k])
	}
	return out
}

func formatURL(host string, port int) string {
	h := strings.TrimSpace(host)
	if h == "" || h == "0.0.0.0" || h == "::" {
		h = "localhost"
	}
	return "http://" + net.JoinHostPort(h, fmt.Sprint(port))
}

func localProbeHost(host string) string {
	h := strings.TrimSpace(host)
	if h == "" || h == "0.0.0.0" {
		return "127.0.0.1"
	}
	if h == "::" || h == "[::]" {
		return "::1"
	}
	return h
}

func waitHTTPReady(ctx context.Context, url string, timeout time.Duration) error {
	if strings.TrimSpace(url) == "" {
		return errors.New("url is required")
	}
	deadline := time.Now().Add(timeout)
	client := &http.Client{Timeout: 2 * time.Second}

	for {
		if ctx != nil && ctx.Err() != nil {
			return ctx.Err()
		}
		req, _ := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
		resp, err := client.Do(req)
		if err == nil && resp != nil {
			_ = resp.Body.Close()
			if resp.StatusCode >= 200 && resp.StatusCode < 500 {
				return nil
			}
		}
		if time.Now().After(deadline) {
			return errors.New("timeout")
		}
		time.Sleep(700 * time.Millisecond)
	}
}
